# Generated by Django 3.1.2 on 2021-04-09 23:00

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210409_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='createdTime',
            field=models.DateTimeField(auto_created=True, default=django.db.models.fields.DateTimeField),
        ),
    ]
