# Generated by Django 3.1.2 on 2021-04-09 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210409_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='createdTime',
            field=models.DateTimeField(db_column='创建时间', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(blank=True, db_column='标题', max_length=100),
        ),
    ]
