# Generated by Django 3.1.2 on 2021-04-09 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210409_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='createdTime',
            field=models.DateTimeField(auto_created=True, db_column='创建时间', default=django.utils.timezone.now),
        ),
    ]
