# Generated by Django 3.1.2 on 2021-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210414_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avatar',
        ),
        migrations.AddField(
            model_name='article',
            name='avatar1',
            field=models.ImageField(blank=True, db_column='标题图1', upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar2',
            field=models.ImageField(blank=True, db_column='标题图2', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar3',
            field=models.ImageField(blank=True, db_column='标题图3', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar4',
            field=models.ImageField(blank=True, db_column='标题图4', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar5',
            field=models.ImageField(blank=True, db_column='标题图5', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar6',
            field=models.ImageField(blank=True, db_column='标题图6', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar7',
            field=models.ImageField(blank=True, db_column='标题图7', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar8',
            field=models.ImageField(blank=True, db_column='标题图8', null=True, upload_to='static/article/%Y%m%d/'),
        ),
        migrations.AddField(
            model_name='article',
            name='avatar9',
            field=models.ImageField(blank=True, db_column='标题图9', null=True, upload_to='static/article/%Y%m%d/'),
        ),
    ]
